# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-14 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('sub_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.Category')),
            ],
            options={
                'db_table': 'sub_menu',
            },
        ),
    ]
