# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-13 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'img',
            },
        ),
    ]
