# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-14 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='detail_url',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
